/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    bookings: Booking;
    students: Student;
    'availability-rules': AvailabilityRule;
    'blocked-dates': BlockedDate;
    services: Service;
    posts: Post;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    students: StudentsSelect<false> | StudentsSelect<true>;
    'availability-rules': AvailabilityRulesSelect<false> | AvailabilityRulesSelect<true>;
    'blocked-dates': BlockedDatesSelect<false> | BlockedDatesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'agenda-settings': AgendaSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'agenda-settings': AgendaSettingsSelect<false> | AgendaSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Cada sesión reservada. Al cambiar el estado a «Confirmada» o «Cancelada» se envía un correo a la familia.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  title?: string | null;
  service: number | Service;
  student: number | Student;
  startAt: string;
  /**
   * Se calcula con la duración del servicio.
   */
  endAt?: string | null;
  status: 'pending' | 'confirmed' | 'cancelled' | 'completed';
  notes?: string | null;
  cancelReason?: string | null;
  studentTimezone?: string | null;
  consentAt?: string | null;
  source?: ('web' | 'admin') | null;
  manageToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Las líneas de servicio que se pueden agendar. Aquí se cambian precios, duración y qué incluye cada paquete.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * Se usa en menús y etiquetas.
   */
  shortName: string;
  /**
   * No cambiarlo una vez publicado: las páginas del sitio lo usan para enlazar.
   */
  slug: string;
  line: 'acompanamiento' | 'clases-de-ingles';
  /**
   * Por ejemplo: Familias con niños de 2 a 6 años.
   */
  audience: string;
  /**
   * Dos frases que aparecen en las tarjetas.
   */
  summary: string;
  /**
   * Párrafo de apertura de la página del servicio.
   */
  valueProposition: string;
  includes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Por ejemplo: 3 sesiones de 45 a 60 minutos.
   */
  sessionsLabel: string;
  format: string;
  /**
   * Define el tamaño de los espacios en la agenda.
   */
  durationMinutes: number;
  /**
   * Déjalo vacío para mostrar «precio por confirmar».
   */
  priceCop?: number | null;
  isLaunchPrice?: boolean | null;
  active?: boolean | null;
  /**
   * Menor número aparece primero.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Datos de contacto del adulto responsable y, si los compartió, del niño o niña. Se crean solos al reservar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students".
 */
export interface Student {
  id: number;
  parentName: string;
  email: string;
  phone?: string | null;
  childName?: string | null;
  childAge?: string | null;
  /**
   * Solo visibles en este panel.
   */
  notes?: string | null;
  consentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Franjas en las que atiendes cada semana. Puedes crear varias para un mismo día, por ejemplo mañana y tarde.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability-rules".
 */
export interface AvailabilityRule {
  id: number;
  label?: string | null;
  weekday: '0' | '1' | '2' | '3' | '4' | '5' | '6';
  startTime: string;
  endTime: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Vacaciones, festivos o compromisos. Durante estos periodos no se ofrecen horarios aunque haya horario semanal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocked-dates".
 */
export interface BlockedDate {
  id: number;
  reason: string;
  startAt: string;
  endAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Artículos y guías de la sección Recursos. Guarda como borrador mientras escribes y publica cuando esté listo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Se genera solo a partir del título si lo dejas vacío.
   */
  slug?: string | null;
  topic: 'adaptacion-escolar' | 'bilinguismo-temprano' | 'clases-de-ingles';
  publishedAt?: string | null;
  /**
   * Aparece en la lista de recursos y en redes al compartir.
   */
  excerpt: string;
  cover?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  instagramUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Fotos e ilustraciones para los recursos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe la imagen para quien no puede verla. Obligatorio por accesibilidad.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Personas con acceso a este panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'students';
        value: number | Student;
      } | null)
    | ({
        relationTo: 'availability-rules';
        value: number | AvailabilityRule;
      } | null)
    | ({
        relationTo: 'blocked-dates';
        value: number | BlockedDate;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  title?: T;
  service?: T;
  student?: T;
  startAt?: T;
  endAt?: T;
  status?: T;
  notes?: T;
  cancelReason?: T;
  studentTimezone?: T;
  consentAt?: T;
  source?: T;
  manageToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students_select".
 */
export interface StudentsSelect<T extends boolean = true> {
  parentName?: T;
  email?: T;
  phone?: T;
  childName?: T;
  childAge?: T;
  notes?: T;
  consentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability-rules_select".
 */
export interface AvailabilityRulesSelect<T extends boolean = true> {
  label?: T;
  weekday?: T;
  startTime?: T;
  endTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocked-dates_select".
 */
export interface BlockedDatesSelect<T extends boolean = true> {
  reason?: T;
  startAt?: T;
  endAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  slug?: T;
  line?: T;
  audience?: T;
  summary?: T;
  valueProposition?: T;
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  sessionsLabel?: T;
  format?: T;
  durationMinutes?: T;
  priceCop?: T;
  isLaunchPrice?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  topic?: T;
  publishedAt?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  instagramUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Datos de contacto y precios que aparecen en todo el sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  contact?: {
    /**
     * Formato internacional sin «+», por ejemplo 573001234567.
     */
    whatsappNumber?: string | null;
    email?: string | null;
    instagramUrl?: string | null;
    /**
     * Aquí llegan los mensajes del formulario y las nuevas reservas. Si está vacío se usa el correo público.
     */
    notifyEmail?: string | null;
  };
  pricing?: {
    launchPriceFrom?: number | null;
    launchPriceTo?: number | null;
    paymentMethods?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Reglas generales de la agenda pública.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agenda-settings".
 */
export interface AgendaSetting {
  id: number;
  /**
   * Nombre IANA. Los horarios semanales se interpretan en esta zona.
   */
  timezone: string;
  slotStepMinutes: number;
  bufferMinutes: number;
  minNoticeHours: number;
  maxDaysAhead: number;
  /**
   * Se muestra en pantalla y en el correo cuando alguien reserva. Ideal para explicar cómo pagar.
   */
  confirmationMessage: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        whatsappNumber?: T;
        email?: T;
        instagramUrl?: T;
        notifyEmail?: T;
      };
  pricing?:
    | T
    | {
        launchPriceFrom?: T;
        launchPriceTo?: T;
        paymentMethods?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agenda-settings_select".
 */
export interface AgendaSettingsSelect<T extends boolean = true> {
  timezone?: T;
  slotStepMinutes?: T;
  bufferMinutes?: T;
  minNoticeHours?: T;
  maxDaysAhead?: T;
  confirmationMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}